name: Deploy VitePress to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Remove existing submodule (if any)
        run: |
          git submodule deinit -f docs/.vitepress/dist
          Remove-Item -Recurse -Force docs\.vitepress\dist

      - name: Initialize and update submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Install dependencies
        run: npm install

      - name: Build the site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
