name: Build and Deploy VitePress

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
      
      - name: Set execute permissions
        run: chmod +x ./node_modules/.bin/vitepress
      
      - name: Build VitePress
        run: npx ./node_modules/.bin/vitepress build
